import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ClabFooter from '@/widgets/ClabFooter'
import ClubHeader from '@/widgets/ClubHeadr'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClubHeader/>
        {children}
        <ClabFooter/>
      </body>
    </html>
  )
}
